In [5]:
# SHAP TREE EXPLAINER

In [18]:
import shap
# import dalex
# import treeinterpreter

In [8]:
# import pickle
!pip install xgboost

  Using cached xgboost-2.0.3-py3-none-win_amd64.whl (99.8 MB)


In [19]:
model="finalized_model_(siamese & fuzzy(only_orginal_name)_data_enh.sav"
champ_model=pickle.load(open(model,"rb"))

# y_test_prob=champ_model.predict_proba(X_test_nov)[:,-1]

In [20]:
import pandas as pd
df_test=pd.read_csv("enhanced_data_nov_test_results_with_predsid.csv")

In [21]:
df_test.shape

(39969, 36)

In [22]:
X_test=df_test[["FINAL_DOB_MATCH","ID_score","SIAMESE_MATCH_SCORE","N_MATCH_SCORE", 'Final_Nysiis_bisim_score']]
y_test=df_test["V_RESOLUTION"]

In [28]:
X_test.loc[0,:]

FINAL_DOB_MATCH              0.500000
ID_score                    -1.000000
SIAMESE_MATCH_SCORE          0.497174
N_MATCH_SCORE               94.000000
Final_Nysiis_bisim_score     0.937500
Name: 0, dtype: float64

## Feature Attribution Technique Using Tree SHAP  

In [33]:
champ_model.get_params()

{'objective': 'binary:logistic',
 'base_score': None,
 'booster': None,
 'callbacks': None,
 'colsample_bylevel': None,
 'colsample_bynode': None,
 'colsample_bytree': None,
 'device': None,
 'early_stopping_rounds': None,
 'enable_categorical': False,
 'eval_metric': None,
 'feature_types': None,
 'gamma': None,
 'grow_policy': None,
 'importance_type': None,
 'interaction_constraints': None,
 'learning_rate': 0.1,
 'max_bin': None,
 'max_cat_threshold': None,
 'max_cat_to_onehot': None,
 'max_delta_step': None,
 'max_depth': 5,
 'max_leaves': None,
 'min_child_weight': None,
 'missing': nan,
 'monotone_constraints': None,
 'multi_strategy': None,
 'n_estimators': 75,
 'n_jobs': None,
 'num_parallel_tree': None,
 'random_state': None,
 'reg_alpha': 5,
 'reg_lambda': 0,
 'sampling_method': None,
 'scale_pos_weight': None,
 'subsample': None,
 'tree_method': None,
 'validate_parameters': None,
 'verbosity': None,
 'class_weight': 'balanced'}

In [34]:
explainer = shap.TreeExplainer(model=champ_model)
                               
shap_values = explainer.shap_values(X_test.loc[0,:])
print(f'Shape of test dataset: {X_test.shape}')
print(f'Type of shap_values: {type(shap_values)}. Length of the list: {len(shap_values)}')
print(f'Shape of shap_values: {np.array(shap_values).shape}')

[23:18:11] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0b3782d1791676daf-1\xgboost\xgboost-ci-windows\src\c_api\c_api.cc:1240: Saving into deprecated binary model format, please consider using `json` or `ubj`. Model format will default to JSON in XGBoost 2.2 if not specified.


TypeError: predict() got an unexpected keyword argument 'ntree_limit'

In [16]:
# Choose an instance to explain (e.g., the first instance in the test set)


# Create a SHAP explainer
explainer = shap.TreeExplainer(model)

# Calculate SHAP values
shap_values = explainer.shap_values(instance_to_explain)
shap_values

[array([-0.03122627, -0.00541958, -0.15474785, -0.14593963]),
 array([0.02906332, 0.00074618, 0.31726498, 0.30034219]),
 array([ 0.00216296,  0.0046734 , -0.16251713, -0.15440256])]

In [51]:
def feature_importance_shapley(x_test_value):
  # Choose an instance to explain (e.g., the first instance in the test set)
  instance_to_explain = x_test_value

  # Create a SHAP explainer
  explainer = shap.TreeExplainer(model)

  # Calculate SHAP values
  shap_values = explainer.shap_values(instance_to_explain)
  lst1 = [shap_values[i].sum() for i in range(len(shap_values))]
  lst1=np.array(lst1)
  ind=lst1.argmax()
  return shap_values[ind]


In [52]:
feature_importance_shapley(X_test[0])

array([0.02906332, 0.00074618, 0.31726498, 0.30034219])

In [53]:
lst1 = [shap_0[i].sum() for i in range(len(shap_0))]
lst1=np.array(lst)
ind=lst1.argmax()
shap_0[ind]

array([0.02906332, 0.00074618, 0.31726498, 0.30034219])

In [54]:
lst_test=[]
for i in range(len((X_test))):
  lst_test.append(feature_importance_shapley(X_test[i]))
lst_test

[array([0.02906332, 0.00074618, 0.31726498, 0.30034219]),
 array([-0.03137525,  0.03574331,  0.3246542 ,  0.3336444 ]),
 array([ 0.06701536, -0.00651715,  0.31608093,  0.27333753]),
 array([0.04370809, 0.00877539, 0.32105286, 0.28388033]),
 array([ 0.03811874, -0.00918532,  0.1678551 ,  0.33062815]),
 array([0.07193664, 0.00094879, 0.29266493, 0.29711631]),
 array([4.08675935e-02, 3.86048526e-05, 3.22646383e-01, 2.93864086e-01]),
 array([ 0.03183174, -0.00772724,  0.26697601,  0.30883615]),
 array([ 0.01331765, -0.06657563,  0.31035856,  0.26031609]),
 array([0.04055662, 0.00611742, 0.31336597, 0.29737665]),
 array([ 0.06039943, -0.01687665,  0.28553507,  0.30085882]),
 array([7.59802904e-02, 1.15454226e-04, 2.92145084e-01, 2.94425838e-01]),
 array([-0.02597756, -0.00225093,  0.31001727,  0.32087789]),
 array([0.07627791, 0.00094879, 0.29101413, 0.29442584]),
 array([0.06138902, 0.0131849 , 0.2928058 , 0.29528695]),
 array([0.01650524, 0.0314087 , 0.33054647, 0.25895626]),
 array([0.05

In [55]:
lst_test=[]
for i in range(len((X_test1))):
  lst_test.append(feature_importance_shapley(X_test1.loc[i]))
lst_test
df = pd.DataFrame(lst_test, columns=feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            0.029063          0.000746           0.317265          0.300342
1           -0.031375          0.035743           0.324654          0.333644
2            0.067015         -0.006517           0.316081          0.273338
3            0.043708          0.008775           0.321053          0.283880
4            0.038119         -0.009185           0.167855          0.330628
5            0.071937          0.000949           0.292665          0.297116
6            0.040868          0.000039           0.322646          0.293864
7            0.031832         -0.007727           0.266976          0.308836
8            0.013318         -0.066576           0.310359          0.260316
9            0.040557          0.006117           0.313366          0.297377
10           0.060399         -0.016877           0.285535          0.300859
11           0.075980          0.000115           0.292145          0.294426
12          -0.025978         -0.002251           0.310017          0.320878
13           0.076278          0.000949           0.291014          0.294426
14           0.061389          0.013185           0.292806          0.295287
15           0.016505          0.031409           0.330546          0.258956
16           0.055871          0.005690           0.335027          0.283328
17           0.040782          0.000883           0.316053          0.299699
18           0.049040          0.000504           0.311721          0.296152
19           0.051837          0.004437           0.328455          0.285188
20           0.076278          0.000949           0.291014          0.294426
21           0.060033          0.016911           0.153010          0.369963
22           0.076278          0.000949           0.291014          0.294426
23           0.051837          0.004437           0.328455          0.285188
24           0.077177         -0.008451           0.340121          0.271070
25           0.037261          0.006240           0.290187          0.306229
26           0.041493         -0.009534           0.319266          0.268692
27           0.057135         -0.007381           0.347253          0.282910
28           0.075980          0.000115           0.292145          0.294426
29           0.076278          0.000949           0.291014          0.294426

## Feature Attribution Technique 2 Using  Tree Interpreter

In [56]:
# !pip install treeinterpreter

In [130]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from treeinterpreter import treeinterpreter as ti

In [131]:
data=load_iris()
X_train,X_test,y_train,y_test=train_test_split(data.data,data.target,test_size=0.3,random_state=42)

In [132]:
model=RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(X_train,y_train)
record_to_explain=X_test[0]

In [133]:
## Use tree interpreter to get the contribution of each feature for final prediction
prediction, bias, contribution = ti.predict(model, record_to_explain.reshape(1, -1))

In [134]:
contri=list()
print('Prediction',prediction[0])
print('bias:',bias[0])
print('Contribution of each feature:',contribution[0])
contri_value=list()
for arr in contribution[0]:
  val=np.round(arr[0],4)
  contri_value.append(val)
  print(f"{arr[0]:.4f}")
for feature,contribution_value in zip(data.feature_names,contribution[0]):
  print(f"{feature}:{contribution_value[0]:.4f}")
  contri.append(contribution_value[0])
print(contri_value)

Prediction [0.   0.97 0.03]
bias: [0.29619048 0.34942857 0.35438095]
Contribution of each feature: [[-0.05474985  0.03909504  0.01565481]
 [-0.01604259  0.02066269 -0.00462011]
 [-0.11954424  0.26824236 -0.14869812]
 [-0.1058538   0.29257133 -0.18671753]]
-0.0547
-0.0160
-0.1195
-0.1059
sepal length (cm):-0.0547
sepal width (cm):-0.0160
petal length (cm):-0.1195
petal width (cm):-0.1059
[-0.0547, -0.016, -0.1195, -0.1059]


In [138]:
def feature_importance_treeinterpreter(x_test_value):
  contri_value=list()
  record_to_explain=x_test_value
  prediction,bias,contribution=ti.predict(model,record_to_explain.reshape(1,-1))
  for arr in contribution[0]:
    val=np.round(arr[0],4)
    contri_value.append(val)
  return contri_value

In [163]:
feature_importance_treeinterpreter(X_test[1])

[-0.0358, 0.0929, 0.2917, 0.3549]

In [165]:
X_test1=pd.DataFrame(X_test,columns=data.feature_names)
X_test1.shape

(45, 4)

In [158]:
contri_value_test=[]
for i in range(len((X_test))):
  contri_value_test.append(feature_importance_treeinterpreter(X_test[i]))
feat_att=pd.DataFrame(contri_value_test,columns=data.feature_names)
feat_att

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             -0.0547           -0.0160            -0.1195           -0.1059
1             -0.0358            0.0929             0.2917            0.3549
2             -0.0540           -0.0053            -0.1122           -0.1246
3             -0.0547           -0.0149            -0.1207           -0.1059
4             -0.0578           -0.0132            -0.1217           -0.1035
5              0.0637            0.0336             0.2967            0.3099
6             -0.0483           -0.0185            -0.1233           -0.1062
7             -0.0602            0.0009            -0.1122           -0.1246
8             -0.0569           -0.0160            -0.1189           -0.1043
9             -0.0547           -0.0195            -0.1161           -0.1059
10            -0.0602            0.0009            -0.1122           -0.1246
11             0.1117           -0.0072             0.2965            0.3028
12            -0.0138            0.0333             0.2951            0.3392
13             0.1117            0.0181             0.2897            0.2844
14             0.1029            0.0255             0.2914            0.2839
15            -0.0651            0.0120            -0.1330           -0.1101
16            -0.0602            0.0009            -0.1122           -0.1246
17            -0.0483           -0.0196            -0.1222           -0.1062
18            -0.0483           -0.0162            -0.1256           -0.1062
19            -0.0540           -0.0053            -0.1122           -0.1246
20             0.1117            0.0181             0.2897            0.2844
21            -0.0572            0.0013            -0.1066           -0.1337
22             0.1029            0.0255             0.2914            0.2839
23            -0.0540           -0.0053            -0.1122           -0.1246
24            -0.0602            0.0084            -0.1205           -0.1239
25            -0.0602            0.0009            -0.1122           -0.1246
26            -0.0540           -0.0053            -0.1122           -0.1246
27            -0.0602            0.0009            -0.1122           -0.1246
28             0.1117           -0.0072             0.2965            0.3028
29             0.1117            0.0181             0.2897            0.2844
30             0.1029            0.0255             0.2914            0.2839
31            -0.0358            0.0929             0.2917            0.3549
32            -0.0641            0.0126            -0.1324           -0.1023
33             0.1029            0.0255             0.2914            0.2839
34             0.1117            0.0181             0.2897            0.2844
35            -0.0538           -0.0055            -0.1054           -0.1315
36            -0.0641            0.0072            -0.1370           -0.1023
37             0.0793            0.0255             0.2966            0.3024
38             0.1029            0.0255             0.2914            0.2839
39             0.0793            0.0255             0.2966            0.3024
40            -0.0509           -0.0059            -0.1126           -0.1268
41            -0.0522            0.0228            -0.1347           -0.1121
42            -0.0641            0.0072            -0.1370           -0.1023
43             0.0637            0.0336             0.2967            0.3099
44             0.0637            0.0336             0.2967            0.3099

In [155]:
def feature_importance_treeinterpreter_df_vectorized(x_test_df, model):
    # Assuming `model` is a trained RandomForestClassifier
    predictions, biases, contributions = ti.predict(model, x_test_df.values)

    # Extract and round the contribution values for each feature
    contri_values = np.round(contributions[:, :, 0], 4).tolist()

    return contri_values

In [166]:
feat_attri=feature_importance_treeinterpreter_df_vectorized(X_test1,model)
pd.DataFrame(feat_attri,columns=data.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0             -0.0547           -0.0160            -0.1195           -0.1059
1             -0.0358            0.0929             0.2917            0.3549
2             -0.0540           -0.0053            -0.1122           -0.1246
3             -0.0547           -0.0149            -0.1207           -0.1059
4             -0.0578           -0.0132            -0.1217           -0.1035
5              0.0637            0.0336             0.2967            0.3099
6             -0.0483           -0.0185            -0.1233           -0.1062
7             -0.0602            0.0009            -0.1122           -0.1246
8             -0.0569           -0.0160            -0.1189           -0.1043
9             -0.0547           -0.0195            -0.1161           -0.1059
10            -0.0602            0.0009            -0.1122           -0.1246
11             0.1117           -0.0072             0.2965            0.3028
12            -0.0138            0.0333             0.2951            0.3392
13             0.1117            0.0181             0.2897            0.2844
14             0.1029            0.0255             0.2914            0.2839
15            -0.0651            0.0120            -0.1330           -0.1101
16            -0.0602            0.0009            -0.1122           -0.1246
17            -0.0483           -0.0196            -0.1222           -0.1062
18            -0.0483           -0.0162            -0.1256           -0.1062
19            -0.0540           -0.0053            -0.1122           -0.1246
20             0.1117            0.0181             0.2897            0.2844
21            -0.0572            0.0013            -0.1066           -0.1337
22             0.1029            0.0255             0.2914            0.2839
23            -0.0540           -0.0053            -0.1122           -0.1246
24            -0.0602            0.0084            -0.1205           -0.1239
25            -0.0602            0.0009            -0.1122           -0.1246
26            -0.0540           -0.0053            -0.1122           -0.1246
27            -0.0602            0.0009            -0.1122           -0.1246
28             0.1117           -0.0072             0.2965            0.3028
29             0.1117            0.0181             0.2897            0.2844
30             0.1029            0.0255             0.2914            0.2839
31            -0.0358            0.0929             0.2917            0.3549
32            -0.0641            0.0126            -0.1324           -0.1023
33             0.1029            0.0255             0.2914            0.2839
34             0.1117            0.0181             0.2897            0.2844
35            -0.0538           -0.0055            -0.1054           -0.1315
36            -0.0641            0.0072            -0.1370           -0.1023
37             0.0793            0.0255             0.2966            0.3024
38             0.1029            0.0255             0.2914            0.2839
39             0.0793            0.0255             0.2966            0.3024
40            -0.0509           -0.0059            -0.1126           -0.1268
41            -0.0522            0.0228            -0.1347           -0.1121
42            -0.0641            0.0072            -0.1370           -0.1023
43             0.0637            0.0336             0.2967            0.3099
44             0.0637            0.0336             0.2967            0.3099

In [167]:
## The psoitive and negative values of treeinterpreter indicates the impact of each feature in model prediction
##Positive value=A positive contribution of a feature means that specific feature had a positive impact on pushing the model's
## output towards a higher value. An increase in the value of a feature contributes to an  increase in the predicted outcome
## Negative Value=Similarly a negative contribution of a specific feature means that specific feature had a negative impact on
## model's prediction and pushes it down to a lower value
# For example, let's say you have a RandomForestClassifier predicting whether a person will buy a product (binary outcome).
# If the contribution of the "Age" feature is positive, it suggests that an increase in age has a positive impact
#  on the likelihood of buying the product. On the other hand, if the contribution is negative,
# it implies that an increase in age has a negative impact on the likelihood of buying the product.

In [168]:
## Just knowing the positive and negative values is not sufficient.We also need to assess the magnitude of this impact

In [170]:
import sys
import treeinterpreter
print(sys.version)
print('TreeInterpreter:',treeinterpreter.__version__)

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
TreeInterpreter: 0.1.0


## Feature Selection technique 3 Using Integrated Gradients


In [53]:
# Integrated Gradients
# PROS:
# 1.Model agnostic , applicable to various model types
# 2.Handles non linear relationships well
# 3.Provides a path dependent explanation,tracing feature attribution along the prediction process
# Cons:
# 1.Can be sensitive to feature scales and normalisation
# 2.May require careful implementation for tree based models

## Feature Selection technique 3 Using Dalex


In [57]:
import xgboost
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from dalex import Explainer

In [58]:
# Load the Iris dataset
data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2, random_state=42)
X_train=pd.DataFrame(X_train)
X_test=pd.DataFrame(X_test)
y_train=pd.DataFrame(y_train)
y_test=pd.DataFrame(y_test)

In [59]:
# Train an XGBoost model
model = xgboost.XGBClassifier(objective="multi:softmax", num_class=3)
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None, num_class=3,
              num_parallel_tree=None, ...)

In [60]:
# Convert X_test to a DataFrame for dalex
X_test_df = pd.DataFrame(X_test, columns=data.feature_names)

In [61]:
# Wrap the XGBoost model using dalex explainer
xgb_explainer = Explainer(model, X_train, y_train, label="XGBoost")


Preparation of a new explainer is initiated

  -> data              : 120 rows 4 cols
  -> target variable   : Parameter 'y' was a pandas.DataFrame. Converted to a numpy.ndarray.
  -> target variable   : 120 values
  -> model_class       : xgboost.sklearn.XGBClassifier (default)
  -> label             : XGBoost
  -> predict function  : <function yhat_proba_default at 0x7a5da94b7640> will be used (default)
  -> predict function  : Accepts pandas.DataFrame and numpy.ndarray.
  -> predicted values  : min = 0.000741, mean = 0.341, max = 0.998
  -> model type        : classification will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -0.00883, mean = 0.65, max = 2.0
  -> model_info        : package xgboost

A new explainer has been created!


In [65]:
# Explain a single prediction (record level)
prediction_instance = X_test[0, :]
local_feature_importance = xgb_explainer.predict_parts(
    new_observation=prediction_instance,
    type="break_down"
)

# Display the local feature importance for the first prediction
print("Local Feature Importance:")
print(local_feature_importance)

InvalidIndexError: (0, slice(None, None, None))

In [82]:
import xgboost
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from dalex import Explainer

# Load the Iris dataset
data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2, random_state=42)

# Train an XGBoost model
model = xgboost.XGBClassifier(objective="multi:softmax", num_class=3)
model.fit(X_train, y_train)

# Convert X_test to a DataFrame for dalex
X_test_df = pd.DataFrame(X_test, columns=data.feature_names)

# Wrap the XGBoost model using dalex explainer
xgb_explainer = Explainer(model, X_train, y_train, label="XGBoost")

# Explain a single prediction (record level)
prediction_instance = X_test_df.iloc[0, :]  # Use iloc directly on the DataFrame
local_feature_importance = xgb_explainer.predict_parts(
    new_observation=prediction_instance,
    type="break_down"
)

# Display the local feature importance for the first prediction
print("Local Feature Importance:")
print(list(local_feature_importance.result.contribution[1:-1]))

Preparation of a new explainer is initiated

  -> data              : numpy.ndarray converted to pandas.DataFrame. Columns are set as string numbers.
  -> data              : 120 rows 4 cols
  -> target variable   : 120 values
  -> model_class       : xgboost.sklearn.XGBClassifier (default)
  -> label             : XGBoost
  -> predict function  : <function yhat_proba_default at 0x7a5da94b7640> will be used (default)
  -> predict function  : Accepts pandas.DataFrame and numpy.ndarray.
  -> predicted values  : min = 0.000741, mean = 0.341, max = 0.998
  -> model type        : classification will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -0.00883, mean = 0.65, max = 2.0
  -> model_info        : package xgboost

A new explainer has been created!
Local Feature Importance:
[0.5076189637184143, 0.13507461547851562, 0.007626533508300781, -0.004936873912811279]


In [83]:
local_feature_importance.result

variable_name variable_value    variable  cumulative  contribution  sign  \
0     intercept                  intercept    0.341330      0.341330   1.0   
1             2            4.7     2 = 4.7    0.848949      0.507619   1.0   
2             3            1.2     3 = 1.2    0.984024      0.135075   1.0   
3             0            6.1     0 = 6.1    0.991650      0.007627   1.0   
4             1            2.8     1 = 2.8    0.986713     -0.004937  -1.0   
5                               prediction    0.986713      0.986713   1.0   

   position    label  
0         5  XGBoost  
1         4  XGBoost  
2         3  XGBoost  
3         2  XGBoost  
4         1  XGBoost  
5         0  XGBoost

In [80]:
list(local_feature_importance.result.contribution[1:-1])

[0.5076189637184143,
 0.13507461547851562,
 0.007626533508300781,
 -0.004936873912811279]

In [84]:
def feature_attribution_dalex(x_test_value_row_number):
  # Wrap the XGBoost model using dalex explainer
  xgb_explainer = Explainer(model, X_train, y_train, label="XGBoost")

  # Explain a single prediction (record level)
  prediction_instance = X_test_df.iloc[x_test_value_row_number, :]  # Use iloc directly on the DataFrame
  local_feature_importance = xgb_explainer.predict_parts(
      new_observation=prediction_instance,
      type="break_down"
  )

  # Display the local feature importance for the first prediction
  contri_value=list(local_feature_importance.result.contribution[1:-1])
  return contri_value

In [86]:
contri_lst=[]
for i in range(len(X_test_df)):
  val_arr=feature_attribution_dalex(i)
  contri_lst.append(val_arr)

Preparation of a new explainer is initiated

  -> data              : numpy.ndarray converted to pandas.DataFrame. Columns are set as string numbers.
  -> data              : 120 rows 4 cols
  -> target variable   : 120 values
  -> model_class       : xgboost.sklearn.XGBClassifier (default)
  -> label             : XGBoost
  -> predict function  : <function yhat_proba_default at 0x7a5da94b7640> will be used (default)
  -> predict function  : Accepts pandas.DataFrame and numpy.ndarray.
  -> predicted values  : min = 0.000741, mean = 0.341, max = 0.998
  -> model type        : classification will be used (default)
  -> residual function : difference between y and yhat (default)
  -> residuals         : min = -0.00883, mean = 0.65, max = 2.0
  -> model_info        : package xgboost

A new explainer has been created!
Preparation of a new explainer is initiated

  -> data              : numpy.ndarray converted to pandas.DataFrame. Columns are set as string numbers.
  -> data              : 

In [91]:
contri_lst=pd.DataFrame(contri_lst)
contri_lst.columns=X_test_df.columns
contri_lst

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            0.507619          0.135075           0.007627         -0.004937
1            0.049332          0.003789           0.017647         -0.403266
2            0.008106         -0.004679          -0.231148         -0.112120
3            0.509340          0.125412           0.013373          0.001843
4            0.417500          0.206588           0.012889         -0.019936
5            0.049332          0.003789           0.001223         -0.391809
6            0.545744          0.103171          -0.000880          0.004439
7            0.018651          0.005078          -0.235734         -0.114634
8            0.509340          0.125412           0.013095         -0.013848
9            0.545071          0.102873           0.004727          0.002844
10           0.022018          0.002254          -0.235908         -0.114354
11           0.049332          0.000967          -0.005814         -0.382905
12           0.049332          0.003789           0.007153         -0.396268
13           0.049332          0.003789          -0.005032         -0.386507
14           0.049332          0.003789          -0.003359         -0.388180
15           0.507619          0.134075           0.005555          0.009052
16           0.006911          0.002476          -0.127147         -0.222603
17           0.545071          0.102873           0.004480          0.000726
18           0.509340          0.136288           0.005942         -0.002032
19           0.006911         -0.014829          -0.262057         -0.070768
20           0.049332          0.003789          -0.005032         -0.386507
21           0.374229         -0.006824           0.001606         -0.651548
22           0.049332          0.003789          -0.005032         -0.386507
23           0.006911         -0.014829          -0.262057         -0.070768
24           0.022018          0.002254          -0.060231         -0.302689
25           0.008106          0.003058          -0.112586         -0.238689
26           0.008106         -0.008561          -0.246459         -0.092949
27           0.022018          0.002254          -0.060231         -0.302689
28           0.049332          0.000967          -0.005814         -0.382905
29           0.049332          0.003789          -0.005032         -0.386507